insert into institutions (code, name, description, category, website_url, associated_court, iban, cod_venit, cui, wait_time_minutes, phone, email, address, latitude, longitude) values
  ('ANPC', 'Autoritatea Națională pentru Protecția Consumatorilor', 'Instituția responsabilă pentru protecția drepturilor consumatorilor.', 'protectia_consumatorului', 'https://anpc.ro', null, null, null, null, 15, '0377 755 100', 'cabinet@anpc.ro', 'Bulevardul Aviatorilor nr. 72, Sector 1, București', 44.4646903, 26.0868814),
  ('ANAF', 'Agenția Națională de Administrare Fiscală', 'Administrează impozitele, taxele și contribuțiile sociale.', 'fiscal', 'https://www.anaf.ro', null, null, null, null, 25, '021 387 10 00', null, 'Str. Apolodor nr. 17, Sector 5, București', 44.4283013, 26.0939112),
  ('PRIMARIE', 'Primăria (generică, locală)', 'Sesizări și amenzi la nivel local; site-ul variază în funcție de localitate.', 'administratie_locala', null, 'Judecătoria de sector/localitate', null, null, null, 40, null, null, null, null, null),
  ('POLITIE_LOCALA', 'Poliția Locală', 'Sesizări stradale și contravenții locale; site-ul variază în funcție de localitate.', 'ordine_publica', null, 'Judecătoria de sector/localitate', null, null, null, 20, null, null, null, null, null),
  ('ANRE', 'Autoritatea Națională de Reglementare în Domeniul Energiei', 'Reglementează piața de energie electrică și gaze naturale.', 'energie', 'https://www.anre.ro', null, null, null, null, 10, '021 327 81 00', 'anre@anre.ro', 'Str. Constantin Nacu nr. 3, Sector 2, București', 44.4370862, 26.1084091),
  ('ANCOM', 'Autoritatea Națională pentru Administrare și Reglementare în Comunicații', 'Reglementează piața de telecomunicații.', 'telecomunicatii', 'https://www.ancom.ro', null, null, null, null, 10, '0372 845 400', 'ancom@ancom.ro', 'Str. Delea Nouă nr. 2, Sector 3, București', 44.4313200, 26.1296408),
  ('CNAS', 'Casa Națională de Asigurări de Sănătate', 'Administrează sistemul de asigurări sociale de sănătate.', 'sanatate', 'https://cnas.ro', null, null, null, null, 30, '0372 309 236', 'contact@cnas.ro', 'Calea Călărași nr. 248, Bl. S19, Sector 3, București', 44.4314537, 26.1360048),
  ('ITM', 'Inspecția Muncii', 'Controlează respectarea legislației muncii.', 'munca', 'https://www.inspectiamuncii.ro', null, null, null, null, 15, '021 302 70 86', null, 'Str. Matei Voievod nr. 14, Sector 2, București', 44.4385245, 26.1247248),
  ('CNCD', 'Consiliul Național pentru Combaterea Discriminării', 'Soluționează sesizări privind fapte de discriminare. Termen legal de depunere: 1 an de la data săvârșirii faptei sau de la data la care persoana lezată putea lua cunoștință de aceasta.', 'discriminare', 'https://www.cncd.ro', null, null, null, null, null, '021 312 65 78', 'support@cncd.ro', 'Piața Valter Mărăcineanu nr. 1-3, Sector 1, București', 44.4374050, 26.0932404),
  ('AVOCATUL_POPORULUI', 'Avocatul Poporului', 'Instituție de mediere între cetățeni și autoritățile publice; emite recomandări, fără forță executorie, pentru apărarea drepturilor și libertăților persoanelor fizice.', 'ombudsman', 'https://avp.ro', null, null, null, null, null, '021 312 71 34', 'petitii@avp.ro', 'Str. George Vraca nr. 8, Sector 1, București', 44.4368737, 26.0953924)
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  website_url = excluded.website_url,
  associated_court = excluded.associated_court,
  iban = excluded.iban,
  cod_venit = excluded.cod_venit,
  cui = excluded.cui,
  wait_time_minutes = excluded.wait_time_minutes,
  phone = excluded.phone,
  email = excluded.email,
  address = excluded.address,
  latitude = excluded.latitude,
  longitude = excluded.longitude;
